/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nanomsg_NanoLibrary */

#ifndef _Included_org_nanomsg_NanoLibrary
#define _Included_org_nanomsg_NanoLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_term
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nanomsg_NanoLibrary_nn_1term
  (JNIEnv *, jobject);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1errno
  (JNIEnv *, jobject);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_nanomsg_NanoLibrary_nn_1strerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_socket
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1socket
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1close
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_bind
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1bind
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_connect
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1connect
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_shutdown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1shutdown
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_send
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1send
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_recv
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1recv
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_sendstr
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1sendstr
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_sendbyte
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1sendbyte
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_recvstr
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_nanomsg_NanoLibrary_nn_1recvstr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_recvbyte
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_nanomsg_NanoLibrary_nn_1recvbyte
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_recvbyteerror
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1recvbyteerror
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_getsockopt_int
 * Signature: (IIILjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1getsockopt_1int
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_setsockopt_int
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1setsockopt_1int
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_setsockopt_str
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1setsockopt_1str
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    nn_poll
 * Signature: ([Lorg/nanomsg/NNPollFD;I)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_nn_1poll
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     org_nanomsg_NanoLibrary
 * Method:    load_symbols
 * Signature: (Ljava/util/Map;)I
 */
JNIEXPORT jint JNICALL Java_org_nanomsg_NanoLibrary_load_1symbols
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
